### ISSUE TITLE
incorporate speculator into fitter

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#7]
**todo**:
- [x] implement priors for the SFH and Z bases
- [x] include log(prior) into posterior
- [x] implement SFR recovery from SFHs
- [x] test fits using speculator
